"use client";

// Thin pass-through ViewModel, matching kit-batch practice: the kit
// piece is fixture-fed and owns no data. Generation availability,
// the coin cost, and every option list are computed by the caller
// (fixture logic, or the Media Studio page's adapter); this hook only
// normalizes display-ready props. Contract 2.0.0 (9 Sep 2026).
export function useKitImageCreatorPanelViewModel({
  mode = "IMAGE",
  onChangeMode = null,
  videoDisabled = true,
  videoSoonLabel = "Soon",
  stage = "GENERATE",
  onChangeStage = null,
  slots = {},
  onSlotActivate = null,
  onSlotClear = null,
  onCustomChangeText = null,
  onCustomBackToPresets = null,
  onCustomSavePreset = null,
  promptValue = "",
  onChangePrompt = null,
  negativePromptValue = "",
  onChangeNegativePrompt = null,
  renderStyleRailProps = null,
  optionFields = [],
  onChangeOption = null,
  advancedTuningProps = null,
  countOptions = [],
  countValue = "",
  onChangeCount = null,
  generateCostLabel = "",
  canGenerate = false,
  generationHelpText = "",
  generationStatus = "idle",
  generationError = "",
  cameraPresetLabel = "Auto / No Camera Filter",
  cameraPresetDescription = "",
  onOpenCameraPresetPicker = null,
  showSceneryOnlyHelper = false,
  sceneryOnlyHelperEnabled = true,
  onChangeSceneryOnlyHelper = null,
  onGenerate = null,
  videoOptionFields = [],
  onChangeVideoOption = null,
  videoDirectionValue = "",
  onChangeVideoDirection = null,
} = {}) {
  return {
    mode: mode === "VIDEO" ? "VIDEO" : "IMAGE",
    onChangeMode,
    videoDisabled: Boolean(videoDisabled),
    videoSoonLabel: String(videoSoonLabel ?? "Soon"),
    stage: stage === "REMIX" ? "REMIX" : "GENERATE",
    onChangeStage,
    slots: slots && typeof slots === "object" ? slots : {},
    onSlotActivate,
    onSlotClear,
    onCustomChangeText,
    onCustomBackToPresets,
    onCustomSavePreset,
    promptValue: promptValue || "",
    onChangePrompt,
    negativePromptValue: negativePromptValue || "",
    onChangeNegativePrompt,
    renderStyleRailProps:
      renderStyleRailProps && typeof renderStyleRailProps === "object"
        ? renderStyleRailProps
        : null,
    optionFields: Array.isArray(optionFields) ? optionFields : [],
    onChangeOption,
    advancedTuningProps:
      advancedTuningProps && typeof advancedTuningProps === "object"
        ? advancedTuningProps
        : null,
    countOptions: Array.isArray(countOptions) ? countOptions : [],
    countValue: String(countValue ?? ""),
    onChangeCount,
    generateCostLabel: String(generateCostLabel ?? ""),
    canGenerate: Boolean(canGenerate),
    generationHelpText: generationHelpText || "",
    generationStatus: String(generationStatus || "idle"),
    generationError: generationError || "",
    cameraPresetLabel: cameraPresetLabel || "Auto / No Camera Filter",
    cameraPresetDescription: cameraPresetDescription || "",
    onOpenCameraPresetPicker,
    showSceneryOnlyHelper: Boolean(showSceneryOnlyHelper),
    sceneryOnlyHelperEnabled: Boolean(sceneryOnlyHelperEnabled),
    onChangeSceneryOnlyHelper,
    onGenerate,
    videoOptionFields: Array.isArray(videoOptionFields) ? videoOptionFields : [],
    onChangeVideoOption,
    videoDirectionValue: videoDirectionValue || "",
    onChangeVideoDirection,
  };
}
