export const CREATION_ASSET_TYPES = [
  "CHARACTER",
  "PLAYER_CHARACTER",
  "SCENARIO",
  "LOCATION",
  "OUTFIT",
  "WARDROBE",
  "POSE",
  "NARRATOR",
  "IMAGE_PRESET",
  "ROOM_TEMPLATE",
  "CHARACTER_TEMPLATE",
  "NPC_REGISTRY",
  "LOCATION_REGISTRY",
  "FACTION_REGISTRY",
  "ORGANIZATION_REGISTRY",
  "EVENT_REGISTRY",
  "QUEST_REGISTRY",
  "ITEM_REGISTRY",
  "STORYLINE",
  "MECHANICS_MODULE",
  "RULES_CODEX",
  "LORE",
  "ACTOR_MECHANICS_PROFILE",
  "STATS_POOLS_PROFILE",
  "PROGRESSION_PROFILE",
];

export const CREATION_TEMPLATE_TYPES = [
  "ROOM_TEMPLATE",
  "CHARACTER_TEMPLATE",
];

export const CREATION_REGISTRY_TYPES = [
  "NPC_REGISTRY",
  "LOCATION_REGISTRY",
  "FACTION_REGISTRY",
  "ORGANIZATION_REGISTRY",
  "EVENT_REGISTRY",
  "QUEST_REGISTRY",
  "ITEM_REGISTRY",
];

export const CREATION_TYPES = [
  ...CREATION_ASSET_TYPES,
  ...CREATION_TEMPLATE_TYPES,
  ...CREATION_REGISTRY_TYPES,
];

export const CREATION_VISIBILITIES = ["PRIVATE", "UNLISTED", "PUBLIC"];

export const OWNER_EDITABLE_VISIBILITIES = ["PRIVATE", "UNLISTED"];

export const CREATION_STATUSES = [
  "DRAFT",
  "IN_REVIEW",
  "APPROVED",
  "REJECTED",
  "ARCHIVED",
];

export const OWNER_EDITABLE_STATUSES = ["DRAFT", "ARCHIVED"];

export const CREATION_CONTENT_RATINGS = ["SFW", "MATURE", "EXPLICIT"];

export const CREATION_CANON_STATUSES = [
  "NONE",
  "CANDIDATE",
  "COMPATIBLE",
  "OFFICIAL",
];

export const CREATION_TITLE_MAX = 140;
export const CREATION_DESCRIPTION_MAX = 2000;