"use client";

// Thin pass-through ViewModel: fixture-fed, owns no data.
export function useKitSaveIngredientPresetViewModel({
  assetLabel = "Asset",
  introText = "",
  message = "",
  messageTone = "info",
  nameValue = "",
  onChangeName = null,
  descriptionValue = "",
  onChangeDescription = null,
  promptValue = "",
  onChangePrompt = null,
  tagsValue = "",
  onChangeTags = null,
  isSaving = false,
  canSave = false,
  canUseOnce = true,
  saveAvailable = true,
  hasUnsavedChanges = false,
  onSavePreset = null,
  onUseOnce = null,
  backLabel = null,
  onClose = null,
} = {}) {
  return {
    assetLabel: assetLabel || "Asset",
    introText: introText || "",
    message: message || "",
    messageTone: messageTone === "error" ? "error" : "info",
    nameValue: nameValue || "",
    onChangeName,
    descriptionValue: descriptionValue || "",
    onChangeDescription,
    promptValue: promptValue || "",
    onChangePrompt,
    tagsValue: tagsValue || "",
    onChangeTags,
    isSaving: Boolean(isSaving),
    canSave: Boolean(canSave),
    canUseOnce: Boolean(canUseOnce),
    saveAvailable: Boolean(saveAvailable),
    hasUnsavedChanges: Boolean(hasUnsavedChanges),
    onSavePreset,
    onUseOnce,
    backLabel: backLabel || null,
    onClose,
  };
}
